# The URL the site will be built for
base_url = "https://odongo.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate Atom and RSS feeds
generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "blackboard-pro"

[extra]
# Put all your custom variables here
mode = "production"
